"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.clearLocalStorage = exports.removeItemLocalStorage = exports.getLocalStorage = exports.setLocalStorage = exports.useLocalStorage = void 0;
var useLocalStorage_1 = require("./components/useLocalStorage");
Object.defineProperty(exports, "useLocalStorage", { enumerable: true, get: function () { return useLocalStorage_1.useLocalStorage; } });
var storage_1 = require("./storage");
Object.defineProperty(exports, "setLocalStorage", { enumerable: true, get: function () { return storage_1.setLocalStorage; } });
Object.defineProperty(exports, "getLocalStorage", { enumerable: true, get: function () { return storage_1.getLocalStorage; } });
Object.defineProperty(exports, "removeItemLocalStorage", { enumerable: true, get: function () { return storage_1.removeItemLocalStorage; } });
Object.defineProperty(exports, "clearLocalStorage", { enumerable: true, get: function () { return storage_1.clearLocalStorage; } });
